### ISSUE TITLE
[OSX] Enhancement: support colour in DTerm

### ISSUE THREAD

**Issue by robrix** [stephencelis/ghi#115]
Decimus’ DTerm[1] is not a real terminal emulator, so stty doesn’t like it; instead of colour support, you get a bunch of lines on stderr:

    stty: stdin isn't a terminal

I’d love it if these could be suppressed; even better would be some way (even if not explicitly for DTerm) to opt ghi into colour support when running within DTerm. 

For example, if I could add something to my .bashrc when TERM_PROGRAM is DTerm to enable colour support in ghi and suppress the stty messages without ghi having to bake-in knowledge about DTerm, that would be more than sufficient. (I do this sort of thing to turn colour on in grep, for example.)

Perhaps a --color option like grep’s?

1: http://decimus.net/DTerm — it’s also on the App Store, for free, which is convenient.

**Comment by AlexChesters** [comment]
This should ideally be implemented by anyone tackling #243 so closing this issue in favour of that one. Thanks!
