### ISSUE TITLE
Task-list support

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [stephencelis/ghi#131]
I'd love to see some integration / support for [GitHub's new task-lists][task lists].

Just some ideas:

 - [ ] Displaying the task-lists associated with an issue
 - [ ] Toggling the completion-state of tasks within an issue that you have the ability to do so within
 - [ ] Listing all the unfinished tasks, across all issues, in the repository
 - [ ] Showing a progress-bar or display of some sort, of the completion of tasks (within a particular issue, or across the entire repository)

   [task lists]: <https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments>

**Comment by AlexChesters** [comment]
Closing as a wontfix.

**Comment by theSwapnilSaste** [comment]
Reopen this issue and assign to me, I have the fix for it.
