### ISSUE TITLE
Aliases under ssh_config break ghi

### ISSUE THREAD

**Issue by philipdexter** [stephencelis/ghi#141]
For example

``` bash
# ~/.ssh/config
Host gh
    HostName github.com
    User git
```

which causes a remote to look like
`origin gh:blah/blah.git`
will cause the logic in ghi to not recognize it as a github repo

**Comment by sgelb** [comment]
SSH aliases can be pretty useful,  e.g for using different accounts on Github, e.g. one for work and one for private projects.
A simple solution for this problem is to set username/repo manually (see #77):
`$ git config ghi.repo username/reponame`
