### ISSUE TITLE
Can't login with two-factor auth

### ISSUE THREAD

**Issue by yoshuawuyts** [stephencelis/ghi#188]
Getting a 'not found' response. Any idea what may cause this? Have tried all username / email + token combinations, and nothing seems to work. Also tried installing through both Brew and Curl. Running `0.9.3`.

**Comment by AlexChesters** [comment]
Hi @nicolaiskogheim,

I've just tried and successfully opened on a private repo that I contribute too but don't own. Does this issue still occur on the latest version of `ghi`?

**Comment by nicolaiskogheim** [comment]
No, it does not! :) Just tried it and everything works like a charm.
Tested creating, deleting and labelling issues on a private repo I don't own, both with https and ssh remote.

For reference:
```
OSX 10.9.5
zsh 5.1.1 (x86_64-apple-darwin13.4.0)
ghi version 0.9.3
```

**Comment by AlexChesters** [comment]
Cool @nicolaiskogheim,

Thanks for that :smile: 

FWIW, `ghi 1.0.0` is now available from Brew :smile: 

Closing this now, if anyone encounters this issue again please feel free to reopen.

**Comment by CheshireSwift** [comment]
Hey, I'm seeing what appears to be the same issue again:

```
$ ghi -vv config --auth CheshireSwift 
===> POST /authorizations {"scopes":["public_repo","repo"],"note":"ghi on MacBook-Pro.local","note_url":"https://github.com/stephencelis/ghi"}
<=== 401: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
                                                     ✔
Bad credentials

$ ghi -v
ghi version 1.2.0
```
