### ISSUE TITLE
`ghi open` prints out "<user> opened this issue 59 minutes from now"

### ISSUE THREAD

**Issue by glittershark** [stephencelis/ghi#194]
Maybe it's a timezone thing, but every time I open an issue the response text reads "glittershark opened this issue 59 minutes from now"

**Comment by AlexChesters** [comment]
Hi @PeterWhittaker @glittershark,

I've just tried this now and it seems okay to me. I'll keep this open to see what happens when BST ends in a few weeks.

**Comment by AlexChesters** [comment]
Closing this as I've tested it again and it still seems fine to me. Please comment if this is still an issue. Thanks!
