### ISSUE TITLE
Can't unassign an issue

### ISSUE THREAD

**Issue by kmcd** [stephencelis/ghi#195]
I'll submit a patch when I'm not as busy in work ...

Here's the error:

 ghi claim 13 --no-assignee
/Users/kmcd/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/ghi-0.9.3/lib/ghi/commands/assign.rb:39:in `execute': undefined method `sub!' for nil:NilClass (NoMethodError)
	from /Users/kmcd/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/ghi-0.9.3/lib/ghi/commands/command.rb:17:in `execute'
	from /Users/kmcd/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/ghi-0.9.3/lib/ghi.rb:80:in `execute'
	from /Users/kmcd/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/ghi-0.9.3/bin/ghi:4:in `<top (required)>'
	from /Users/kmcd/.rbenv/versions/1.9.3-p484/bin/ghi:23:in `load'
	from /Users/kmcd/.rbenv/versions/1.9.3-p484/bin/ghi:23:in `<main>'

**Comment by AlexChesters** [comment]
This issue has been resolved as of 257375e12af74b9ac5227c05f413827ee2a15f8c
