### ISSUE TITLE
Not possible to create issue while in working branch

### ISSUE THREAD

**Issue by caifara** [stephencelis/ghi#198]
When working in a feature branch, `ghi open -m "message"` should, in my opinion, create a new issue. Instead, it infers the current issue number and tries to reopen it.

So this is not a bug, but I've never tried to reopen an issue using ghi and constantly run into wanting to create an issue while working on another one.

**Comment by glittershark** [comment]
:+1:

**Comment by AlexChesters** [comment]
@glittershark's [pull request](https://github.com/stephencelis/ghi/pull/224) seems like a good solution to this. Once that PR has updated the `README` I'd be happy to merge.

**Comment by AlexChesters** [comment]
Closing as this has now been merged

**Comment by pjf** [comment]
Hooray! Thank you!! :)

**Comment by AlexChesters** [comment]
You're welcome @pjf :smile:

**Comment by caifara** [comment]
Great news, thanks!

**Comment by AlexChesters** [comment]
@caifara :smile:
