### ISSUE TITLE
suggestion: assign to self with `ghi new -m "message" --assign`

### ISSUE THREAD

**Issue by caifara** [stephencelis/ghi#203]
Now, one has to use `ghi new -m "message" --claim`, but you can use `ghi assign` inside a branch like `12-issue-name`. So I thought it would be nice if  `ghi new -m "message" --assign` would also assign to self without specifying the username.

**Comment by AlexChesters** [comment]
Hi,

I don't see any real benefit in modifying a the name of this command. I believe `--assign` makes it sound like you are expected to name the user you are assigning, given the `--claim` already exists there are no current plans to change this.
