### ISSUE TITLE
Open repository remote in the browser from the CLI

### ISSUE THREAD

**Issue by RichardLitt** [stephencelis/ghi#208]
I was thinking that it would be really awesome if you could refer to package.json in an npm package, or to other for other managers, like gulp's gulpfile.js. Ideally, the functionality would work like this:

```ghi npm```

Then, you would be able to find the package.json for the directory you're in, or the first in the hierarchy, and search for the repository for that module. Then you could, for instance, do ghi npm open 'foo', etc. 

Figured I would open this here before tackling the code in case this sounds like a good idea or not. Thoughts?

**Comment by AlexChesters** [comment]
Hi @RichardLitt,

Thanks for the idea! I'm not too sure what you mean by this. Do you mean opening by using the remote defined in the `package.json`?

**Comment by RichardLitt** [comment]
Wow, sorry, that was a poorly phrased issue. 

### What

I want to be able to type `ghi remote` to automatically open the GitHub repository's page in the browser. 

### Why

Because I often want to use the GitHub interface, and `ghi` doesn't have all of the functionality or UI that I would like. 

### Comments

* I had no idea why I decided you need `package.json` to do this - it's in the .gitconfig, we should just use that. I also have no idea what I meant by gulpfile.js. 
* I already have this functionality from using [git-extras](https://github.com/tj/git-extras), so this isn't needed anymore, really. This issue should probably just be closed.

**Comment by AlexChesters** [comment]
Thanks for that @RichardLitt!

This is actually quite a nice feature and one I'll probably look at implementing it. If there's any additional functionality that you would like from `ghi` please raise more issues like this one :smile: 

This sounds like a desirable feature though, and one I will (or someone else if they want to contribute) take a look at!

**Comment by AlexChesters** [comment]
@RichardLitt it turns out that this functionality is already present :smile: 

The command you're looking for is `ghi list -w` :smile:

**Comment by RichardLitt** [comment]
Nice! Alright then, all good.

**Comment by AlexChesters** [comment]
FWIW @RichardLitt the `-w` flag is present on most commands and can be loosely interpreted as "_open my current context in a web browser_". I.e. if you run `ghi open -w` it will open a web browser for creating a new issue :-)

**Comment by RichardLitt** [comment]
Cool. Thanks!
