### ISSUE TITLE
Rate Limit exceeded

### ISSUE THREAD

**Issue by RichardLitt** [stephencelis/ghi#212]
So, I've been using `printf "%s\0" "a" "b" "c" | xargs -0 -n1 ghi open --label=Test` to create a bunch of issues from a list. However, after around 25 issues being created, I got this message:

`You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.`

I'm not sure why that is happening: the rate limit is 5000 per hour for authenticated users, and 60 per hours for unauthenticated. I ran this:

```sh
14:42 $ curl -i https://api.github.com/users/RichardLitt
HTTP/1.1 200 OK
Server: GitHub.com
Date: Sun, 21 Dec 2014 22:43:17 GMT
Content-Type: application/json; charset=utf-8
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 55
X-RateLimit-Reset: 1419204236
```

Which shows that I wasn't hitting the unauthenticated Rate Limit, but rather some other unspecified limit. 

Do you any idea why this is happening? Shouldn't my requests always be authenticated? I suspect there is a per-second rate limit in GitHub that isn't in the docs, but I'm not sure.

**Comment by aureooms** [comment]
see https://developer.github.com/v3/#abuse-rate-limits and https://github.com/octokit/octokit.net/issues/638

**Comment by RichardLitt** [comment]
Thanks. I've requested they change their docs to explicitly state their hidden API limits.
