### ISSUE TITLE
How do I assign new colored label?

### ISSUE THREAD

**Issue by tristanwietsma** [stephencelis/ghi#213]
I tried this:

```bash
$ ghi label 112 --add --color f6f6f6 triaged
Issue #112 labeled  triaged .
```

but ``` triaged ``` is white. when i try to modify, it errors.

```bash
$ ghi label triaged -c f6f6f6
(Inferring issue from branch prefix: #109)
Invalid request.

Expected data to be of type "string"; value was: ["triaged"].
```

Seems like my commands match up with usage... Am I missing something?

**Comment by tristanwietsma** [comment]
Also, tried the standard colors (eb6420), same error.

**Comment by stephencelis** [comment]
@tristanwietsma It appears to be working for me:

![screen shot 2015-01-19 at 10 07 26 am](https://cloud.githubusercontent.com/assets/658/5805368/014bb3e8-9fc3-11e4-94fe-2032890c5c06.png)

The terminal only supports 256 colors, so `ghi` will display very light grays as white, etc.

**Comment by tristanwietsma** [comment]
thanks; terminal settings. my bad.
