### ISSUE TITLE
ghi edit help implies positional arguments - but gets them backwards

### ISSUE THREAD

**Issue by PeterWhittaker** [stephencelis/ghi#215]
I wanted to associated milestone 2 with issue 49. Based on

```
usage: ghi edit [options] <issueno>

    -M, --[no-]milestone [<n>]       associate with milestone
```
I tried `ghi edit -M 2 49`; that generated an error that milestone 49 does not exist (which is correct, thank goodness). `ghi edit 49 -M 2` works, but the help (`ghi edit [options] <issueno>`) implies that the issue number should come last.

**Comment by AlexChesters** [comment]
Hi @PeterWhittaker,

I'm not too sure what the issue is here. When I run the following I don't encounter any issues:

```shell
ghi edit -M 215
```

When you mention this command:

```shell
ghi edit -M 2 49
```

Why are you passing in three arguments? (`-M`, `2` and `49`)?
`ghi edit` only takes two arguments

**Comment by PeterWhittaker** [comment]
Well, no, edit takes multiple arguments, depending on which options are used. The usage quoted above implies (well, "explies" :->, it's quite explicit) that edit takes three arguments in that case: the issue number (which comes last, the implication is that it is positional), the milestone option, --milestone, and the milestone number.

It may be purely a documentation issue: Adding and removing milestones to issues appears arcane, but cannot be that complicated....

**Comment by AlexChesters** [comment]
Hi @PeterWhittaker,

Apologies, I didn't understand you originally. I agree this is misleading. I'll update the behaviour of `ghi edit help` now!

**Comment by PeterWhittaker** [comment]
Thanks, Alex!
