### ISSUE TITLE
More verbose error message when ghi edit fails

### ISSUE THREAD

**Issue by PeterWhittaker** [stephencelis/ghi#216]
I tried a number of variations of `ghi edit` to remove a milestone from an issue; all variations resulted in the same error,
```sh
Invalid request.

Expected data to be of type "integer/string/null"; value was: false.
```
The three variations I tried were:
```sh
ghi edit 45 --no-milestone
ghi edit 45 --no-milestone 1
ghi edit 45 --no-milestone 1 45
```
In all three cases I was attempting to remove milestone 1 from issue 45.

**Comment by PeterWhittaker** [comment]
Just found out by accident that `ghi edit 45 -M` was the command I was looking for.

A friendlier message about `too many arguments` might be good, but at least I know how to do what I wanted now.... :->

**Comment by AlexChesters** [comment]
Hi @PeterWhittaker,

This sounds reasonable to me. Would you mind opening a PR for this? Thanks!

**Comment by PeterWhittaker** [comment]
Alex, I'm not a Ruby guy and would be tremendously hesitant to make code changes.

**Comment by AlexChesters** [comment]
I'm going to close this as a won't fix as it's an unlikely edge case and the correct behaviour is covered by `ghi edit --help`.
