### ISSUE TITLE
Error in some repos

### ISSUE THREAD

**Issue by adius** [stephencelis/ghi#218]
I get this error in some repos when executing `$ ghi`:
```
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
```

**Comment by ErebusBat** [comment]
See #189, specifically [this comment](https://github.com/stephencelis/ghi/issues/189#issuecomment-48090882)

**Comment by AlexChesters** [comment]
As @ErebusBat said, you should look at [this](https://github.com/stephencelis/ghi/issues/189#issuecomment-48090882)
