### ISSUE TITLE
error: unknown option `local' output when running 'ghi list'

### ISSUE THREAD

**Issue by vpedabal** [stephencelis/ghi#219]
Running a ghi list outputs some git error messages before listing the outstanding issues.

[ghi]$ ghi list
error: unknown option `local'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    -f, --file <FILE>     use given config file

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 adds a new variable: name value
    --unset               removes a variable: name [value-regex]
    --unset-all           removes all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            opens an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte

# stephencelis/ghi open issues
  218: Error in some repos
  217: Add sort-by-milestone to ghi list
  216: ghi throws parse error when attempting to remove milestone from issue 1
.
.
.

**Comment by PeterWhittaker** [comment]
Vineet, I've not seen this behaviour: `ghi list` works as expected both in git repos (lists issues) and outside of repos (lists nothing); in neither case do I get errors.

Is this new behaviour for you? Or has it been this way since you installed ghi? Do other commands, e.g., `ghi open`, have the same behaviour? Did your initial configuration of ghi complete without errors?

Can you provide the output of the following commands, just to simplify diagnostics?

```
echo $PATH
which git
which ghi
```

**Comment by vpedabal** [comment]
I think I hadn't installed ghi properly in my system. curl couldn't download due to an incorrect proxy, and I had to download it manually. Fixing the proxy helped installing it. And it works perfectly now. Sorry for the false alarm

**Comment by PeterWhittaker** [comment]
No worries - that sort of thing happens.
