### ISSUE TITLE
What do the -p|--paginate|--no-pager options do? (add to README)

### ISSUE THREAD

**Issue by nodiscc** [stephencelis/ghi#220]
Hi, I couldn't find any doc on what these options do. The long options seem to be broken (I installed from the current `master`):

    Invalid option: --paginate
    Invalid option: --no-pager

The `--no-truncate` option is also not referenced in the readme. @stephencelis can you give me a short explanation of the first two? I'll send a Pull Request if needed.

**Comment by stephencelis** [comment]
It's a top-level option that mirrors the same option on the `git` executable. _E.g._, the following won't feed items into `less`.

``` sh
$ ghi --no-pager list -- rails/rails
```

Meanwhile, `--paginate` will.

It's already documented if you run `man ghi`.

**Comment by nodiscc** [comment]
Thanks @stephencelis I guess I was forgetting the `list` command (since it's the default, ghi doesn't complain when there are no options but `--paginate` makes it fail).

I can't use the manpage (because it's not installed, I used the install procedure described on your README :/). The only available help for me is `ghi --help`... you may want to update the help text.

**Comment by stephencelis** [comment]
The `--help` should illustrate where the options go, too, although it's a bit obtuse:

```
usage: ghi [--version] [-p|--paginate|--no-pager] [--help] <command> [<args>]
           [ -- [<user>/]<repo>]
```

Note the positions of the given flags. They must come before the command to work.

**Comment by nodiscc** [comment]
Yes! Thanks for your help. I should rtfm better. I see that the `--notruncate` option [has been deprecated](https://github.com/stephencelis/ghi/pull/139), and tty detection works as expected. Sorry for the noise.
