### ISSUE TITLE
cannot load such file -- pygments (LoadError)

### ISSUE THREAD

**Issue by raine** [stephencelis/ghi#221]
I installed ghi with brew and got this:

```
~/g/LiveScript git:master ❯❯❯ ghi open                                                       ✖ ✱
/Users/rainevi/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pygments (LoadError)
        from /Users/rainevi/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/bin/ghi:1794:in `highlighter'
        from /usr/local/bin/ghi:1526:in `highlight'
        from /usr/local/bin/ghi:2300:in `block in format_markdown'
        from /usr/local/bin/ghi:2299:in `gsub!'
        from /usr/local/bin/ghi:2299:in `format_markdown'
        from /usr/local/bin/ghi:1942:in `indent'
        from (erb):10:in `format_issue'
        from /Users/rainevi/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/erb.rb:850:in `eval'
        from /Users/rainevi/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/erb.rb:850:in `result'
        from /usr/local/bin/ghi:2049:in `format_issue'
        from /usr/local/bin/ghi:4051:in `execute'
        from /usr/local/bin/ghi:2745:in `execute'
        from /usr/local/bin/ghi:91:in `execute'
        from /usr/local/bin/ghi:4133:in `<main>'
```

**Comment by ErebusBat** [comment]
Did you install the pygments gem as mentioned in the README?

**Comment by AlexChesters** [comment]
Installing pygments should fix this. Please reopen if this is not the case.

**Comment by xerosanyam** [comment]
I got this same problem. I tried following:
sudo apt-get install python-pygments
sudo gem install rb-pygments
But still it doesn't work

**Comment by AlexChesters** [comment]
@xerosanyam did those packages install successfully?

If so, can you comment your output please?

Thanks!

**Comment by jeromefaria** [comment]
I was having the same issue while running `jekyll server --drafts` on OS X 10.11.2 Beta (15C48a) and the solution was:

```sudo gem install pygments.rb```

**Comment by AlexChesters** [comment]
Closing this as this issue is getting a bit dormant now. If this is still an issue for people please comment and we will reopen. Thanks!

**Comment by Karlheinzniebuhr** [comment]
getting the same issue after installing and running bundle install

**Comment by AlexChesters** [comment]
@Karlheinzniebuhr have you tried running `gem install pygments`?

**Comment by Karlheinzniebuhr** [comment]
Yes, that didn’t solve it. Solved it by downgrading to Jekyll v 2.4

**Comment by AlexChesters** [comment]
Okay @Karlheinzniebuhr, thanks for that! Closing this now.

**Comment by Karlheinzniebuhr** [comment]
Thanks @AlexChesters

**Comment by Risto-Stevcev** [comment]
The way I solved this was just to have bundler manage it:

Gemfile
```
source 'https://rubygems.org'
gem 'github-pages', '72'
gem 'pygments.rb'
```

```bash
$ bundle install
```

```bash
$ bundle exec jekyll serve
```
