### ISSUE TITLE
Add `ghi help --commands` …

### ISSUE THREAD

**Issue by Zearin** [stephencelis/ghi#226]
…As an option to quickly list all commands and their one-liner description.  

It would save me frequent trips to the manpage.

**Comment by Phrohdoh** [comment]
`ghi help` is shorter an already exist.

**Comment by AlexChesters** [comment]
Closing this as I believe `ghi help` provides the information you're looking for. If you believe `ghi help` should provide more information please provide examples in another issue and I will take a look :-)

Thanks!
