### ISSUE TITLE
Control issues config from ghi

### ISSUE THREAD

**Issue by albfan** [stephencelis/ghi#239]
Have you think about add a bunch of commands like 

    $ ghi status  #are issues enabled? 
    $ ghi enable #enable issues
    $ ghi disable

to control issues on repo?. If it's possible I would like to avoid to go to web to enable issues.

Using api this action is straight

    $ curl --user <user:pass or oauth> --data '{"name":"<repo>","has_issues":"true"}' https://api.github.com/repos/<user>/<repo>

If you find interesting I can provide a PR.

**Comment by AlexChesters** [comment]
Hi @albfan,

This certainly sounds like a very nice idea. I'd be very interested in a PR you could provide? :smile:

**Comment by AlexChesters** [comment]
So I've done the first piece of work for this, `ghi status` can now be used to tell you whether or not issues are enabled for the current repo or not :smile:

**Comment by albfan** [comment]
Great. Expect any PR from my side for next week. If you have status I suppose almost all work is done at this point so finish it if you can

**Comment by AlexChesters** [comment]
Yeah I've just finished the work for this now so this will go up in the next release! Thanks for the suggestion :smile:

**Comment by albfan** [comment]
Great. This rocks!. Cool to see internals from commits. Now is easy to propose something from a fork.
