### ISSUE TITLE
list -S updated doesn't work

### ISSUE THREAD

**Issue by chdiza** [stephencelis/ghi#240]
I have found that `ghi list -S updated -- somerepo` does not sort the issues by "updated", but sorts them merely by their issue/PR numbers, descending.

You can verify this by looking at any repo where the "most recently updated" ordering is different from the  ID-numbering.

**Comment by AlexChesters** [comment]
Can you provide a repo which has an example of this?

**Comment by chdiza** [comment]
> Can you provide a repo which has an example of this?

Any repo where the "most recently updated" ordering shown on the GitHub webpage is different from the ID-numerbing.  Typically, `Homebrew/homebrew` as several instances of this on the first web-page-full of issues.

**Comment by chdiza** [comment]
Or even as of this moment, the `stephencelis/ghi` repo is like this.  `ghi` on that repo simply shows the issues in reverse ID-number order, not according to whether they're recently updated.  E.g., as of right now #208 is second on the list of recently-updated issues, but way down on the output of `ghi`,

**Comment by AlexChesters** [comment]
Hi @chdiza,

It looks like this issue is with the Github API itself.

If you compare the output of `ghi list -S updated` for this repo and the [api result](https://api.github.com/repos/stephencelis/ghi/issues?sort=updated)

You'll see that they match up

**Comment by chdiza** [comment]
I don't think this should be closed, especially since the exact same problem occurs with `list -S comments`.  (Do `ghi list -S comments -- Homebrew/homebrew`, e.g., and observe that the issues are not sorted by the number of comments.)

If this really is the GitHub API's fault, that's fine, but then `ghi` shouldn't be advertising that it can sort by `updated` or `comments`.

**Comment by AlexChesters** [comment]
Fair point @chdiza,

I've reopened this with a won't fix as there really isn't anything we can do about it. We're making the correct API calls according to the [docs](https://developer.github.com/v3/issues/#list-issues)

**Comment by chdiza** [comment]
The ghi team can't make the functionality work, but I suggest changing `ghi help list` so that `updated` and `comments` are not advertised as things ghi can do.  This could be either stripping mention of them out entirely, or by noting that they don't work anymore.

**Comment by AlexChesters** [comment]
@chdiza I think a sensible approach would be modifying the help documentation to state that they aren't currently working due to an issue with the GitHub api, but maybe @stephencelis should decide this!
