### ISSUE TITLE
New release to pick up features from PR#237 ?

### ISSUE THREAD

**Issue by Dangeranger** [stephencelis/ghi#244]
Hello,

I just installed this gem using Homebrew and was excited to use the features around listing issues assigned to me from organizations that I am a part of. It appears that these features are pushed to master in PR https://github.com/stephencelis/ghi/pull/237 but not yet released on a tag.

Could you make a new tagged release so that the an update can be made to the brew install recipe? 

Thanks for all the work.

**Comment by AlexChesters** [comment]
Hi @Dangeranger,

I've made a new tagged release for 0.9.4 which is awaiting merging into Homebrew now :-)

https://github.com/Homebrew/homebrew/pull/45032
