### ISSUE TITLE
SHOW not working and EDIT crashes

### ISSUE THREAD

**Issue by lpanebr** [stephencelis/ghi#245]
What is the problem?

**SHOW:**
```bash
(master)$ ghi show 3
(master)$ 
```

**EDIT:**
```bash
(master)$ ghi edit 3
/var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting.rb:457:in `format_markdown': undefined (?...) sequence: /(?<indent>^\ {0})(```)\s*(?<lang>\w*$)(\n)(?<code>.+?)(\n)(^\ {0}```$)/ (Reg
expError)
        from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting.rb:100:in `indent'
        from (erb):1:in `format_issue'
        from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting/colors.rb:47:in `no_color'
        from (erb):1:in `format_issue'
        from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting/colors.rb:225:in `escape'
        from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting/colors.rb:25:in `bright'
        from (erb):1:in `format_issue'
        from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting.rb:207:in `format_issue'
        from (erb):10:in `format_editor'
        from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting/colors.rb:47:in `no_color'
        from (erb):10:in `format_editor'
        from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/formatting.rb:362:in `format_editor'
        from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/commands/edit.rb:74:in `execute'
        from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi/commands/command.rb:17:in `execute'
        from /var/lib/gems/1.8/gems/ghi-0.9.3/lib/ghi.rb:80:in `execute'
        from /var/lib/gems/1.8/gems/ghi-0.9.3/bin/ghi:4
        from /usr/local/bin/ghi:19:in `load'
        from /usr/local/bin/ghi:19
(master)$ 
```

**Comment by AlexChesters** [comment]
I'm unable to reproduce this issue. Does issue number 3 exist on the repo you are running this in?

**Comment by lpanebr** [comment]
Issue 3?
Spec coverage for the CLI layer #3

This one?
I don't understand it..

Em sex, 16 de out de 2015 12:05, Alex Chesters <notifications@github.com>
escreveu:

> I'm unable to reproduce this issue. Does issue number 3 exist on the repo
> you are running this in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stephencelis/ghi/issues/245#issuecomment-148741146>.
>
-- 

Atenciosamente,


*Luciano Panepucci*Cofundador e Diretor de Tecnologia
+55 (16) 3307-2068 | +55 (16) 991 728 681 | skype: lpanebr


*Editora Cubo*soluções para o universo acadêmico
Rua Marechal Deodoro 2709
13560-201 São Carlos - SP
www.editoracubo.com.br

**Comment by AlexChesters** [comment]
I'm unable to reproduce this. Can you verify what version of ghi you're running?

`ghi -v`

**Comment by AlexChesters** [comment]
This is a strange one. I'll be honest I have no idea what line 457 of `formatting.rb` does as I didn't write it. @stephencelis may be able to advise!

**Comment by lpanebr** [comment]
Let me know if you need some additional tests..

**Comment by AlexChesters** [comment]
I'm assuming the error caused when you try to edit #3 is because you don't have the necessary permissions to edit issues on this project?

**Comment by AlexChesters** [comment]
@lpanebr does `ghi edit <issuenumber>` work on a repository for which you have push access?

**Comment by lpanebr** [comment]
No, it does not work.

Issue 14 exists on the repo and I am the repo owner with full rights.

![image](https://cloud.githubusercontent.com/assets/129185/10576031/362ebf08-763f-11e5-9907-292927ec5c94.png)

One thing that I just realized. This is a private repo!

**Comment by AlexChesters** [comment]
@lpanebr interesting... What happens if you run `git conifg --auth` inside said repo?

**Comment by lpanebr** [comment]
It complains about `error: unknown option `auth'`

![image](https://cloud.githubusercontent.com/assets/129185/10584347/7cd8f528-7670-11e5-8e9d-488edac38f4a.png)

This may be useful:
![image](https://cloud.githubusercontent.com/assets/129185/10584382/b8231c3a-7670-11e5-90ee-0191c61e8565.png)

**Comment by AlexChesters** [comment]
@lpanebr d'oh, silly me! I meant `ghi config --auth`!

**Comment by lpanebr** [comment]
oh.. this is what happens:

![image](https://cloud.githubusercontent.com/assets/129185/10584805/d05e8012-7672-11e5-9158-57da2fe8b300.png)

**Comment by AlexChesters** [comment]
@lpanebr can you go [here](https://github.com/settings/tokens) and remove any tokens that mention `ghi`?

**Comment by lpanebr** [comment]
Just did it.. Should I run `ghi config --auth` again?

**Comment by AlexChesters** [comment]
Yes please @lpanebr :smile:

**Comment by lpanebr** [comment]
ok. Here's what happened:

![image](https://cloud.githubusercontent.com/assets/129185/10584977/e5a01f34-7673-11e5-9217-2c1f7e14eb7f.png)

And nothing new appeared on my https://github.com/settings/tokens

**Comment by AlexChesters** [comment]
Interesting, same as #211... What version of ruby are you running?

**Comment by lpanebr** [comment]
```bash
$ ruby --version # tab tab
ruby       ruby1.8    ruby1.9.1
$ ruby --version
ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]
```

**Comment by AlexChesters** [comment]
@lpanebr could you see if the same thing happens with Ruby v.2 or greater?

**Comment by lpanebr** [comment]
hmmm..... now you got me on my Achilles heel... 

I am such a lousy dev and sysadmin... 

I don't know if I know how to upgrade.... :-(

**Comment by AlexChesters** [comment]
@lpanebr thankfully it's relatively painless :smile: 

Do you `rvm` installed? (Does `rvm` in the terminal do anything?)

**Comment by lpanebr** [comment]
I "heard" of this already.. but no..

```
$ rvm
The program 'rvm' is currently not installed.  You can install it by typing
sudo apt-get install ruby-rvm
```

Is it realy that simple? Install and I am ready?

**Comment by AlexChesters** [comment]
@lpanebr almost! First step you'll want to install that, then you'll want to install Ruby 2.2.0, then you'll want to switch to using that version of Ruby. These commands will do the trick!

`sudo apt-get install ruby-rvm` - Install `rvm`
`rvm install 2.2.0` - Install Ruby v2.2.0, this might take a while!
`rvm use 2.2.0` - Now run `ghi config --auth` again :smile: 

`rvm` stands for Ruby Version Manager and is a nice way of quickly changing your Ruby version on the command line. In future if you ever want to switch what version of ruby you are using, just run `rvm use <ruby-version>` :smile:

**Comment by lpanebr** [comment]
Step 1. seemed to finish fine:
![image](https://cloud.githubusercontent.com/assets/129185/10585894/5d77d25a-7678-11e5-8288-bc72bbcdb2c3.png)

But then step 2:
![image](https://cloud.githubusercontent.com/assets/129185/10585909/6b41d9a8-7678-11e5-90e3-91e3a329440e.png)

![image](https://cloud.githubusercontent.com/assets/129185/10585911/72fbd9b4-7678-11e5-895b-dfe181512f9b.png)

**Comment by AlexChesters** [comment]
@lpanebr that's strange.. Is the last screenshot the result of typing `rvm` into your terminal?

**Comment by lpanebr** [comment]
yes...

**Comment by AlexChesters** [comment]
@lpanebr can you run the following command?

`\curl -sSL https://get.rvm.io | bash -s stable --ruby`

**Comment by lpanebr** [comment]
This does not look good... :-/

```
It looks you are one of the happy Ubuntu users,
RVM packaged by Ubuntu is old and broken,
follow this link for details how to fix:

  http://stackoverflow.com/a/9056395/497756
```

**Comment by lpanebr** [comment]
I will try that to fix it..

**Comment by AlexChesters** [comment]
Ahh, nice :disappointed: 

I'm on OS X so I may be little help when it comes to Linux issues!

**Comment by lpanebr** [comment]
Good news: I got it installed and running!

![image](https://cloud.githubusercontent.com/assets/129185/10587027/14d68284-767e-11e5-8585-e009cdbeddff.png)

Bad news: It got worse. Now `ghi` always crashes... `ghi config --auth` also crashes

![image](https://cloud.githubusercontent.com/assets/129185/10587057/330fbafe-767e-11e5-8aec-8779689678d9.png)

**Comment by AlexChesters** [comment]
@lpanebr can you post a screenshot the includes all of that first line?

**Comment by lpanebr** [comment]
There you have it:

```
 (develop)$ ghi
/usr/lib/ruby/vendor_ruby/1.8/rubygems/dependency.rb:247:in `to_specs':
Could not find ghi (>= 0) amongst [bundler-1.8.4, bundler-unload-1.0.2,
executable-hooks-1.3.2, gem-wrappers-1.2.7, minitest-5.4.3,
power_assert-0.2.2, rubygems-bundler-1.4.4, rvm-1.11.3.9, test-unit-3.0.8]
(Gem::LoadError)
from /usr/lib/ruby/vendor_ruby/1.8/rubygems/dependency.rb:256:in `to_spec'
from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:1208:in `gem'
from /usr/local/bin/ghi:18
```

**Comment by AlexChesters** [comment]
@lpanebr so Ruby Gems are specific to each version of Ruby. So now that you're using Ruby 2.2.0 you won't have any gems installed. You'll need to run `gem install ghi` again.

**Comment by lpanebr** [comment]
I installed it. 

Did  the `ghi config --auth`

Now I get:

```bash
$ ghi show 49 # no output ...
$ ghi edit 49 # error output                                                                                                                                                                  
/home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi/formatting.rb:467:in `format_markdown': undefined (?...) sequence: /(?<indent>^\ {0})(```)\s*(?<lang>\w*$)(\n)(?<code>.+?)(\n)(^\ {0}```$)/ (RegexpError)
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi/formatting.rb:102:in `indent'
        from (erb):1:in `format_issue'
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi/formatting/colors.rb:47:in `no_color'
        from (erb):1:in `format_issue'
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi/formatting/colors.rb:225:in `escape'
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi/formatting/colors.rb:25:in `bright'
        from (erb):1:in `format_issue'
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi/formatting.rb:212:in `format_issue'
        from (erb):11:in `format_editor'
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi/formatting/colors.rb:47:in `no_color'
        from (erb):11:in `format_editor'
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi/formatting.rb:367:in `format_editor'
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi/commands/edit.rb:74:in `execute'
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi/commands/command.rb:17:in `execute'
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/lib/ghi.rb:80:in `execute'
        from /home/lpanebr/.rvm/gems/ruby-2.2.1/gems/ghi-1.0.2/bin/ghi:4
        from /usr/local/bin/ghi:19:in `load'
        from /usr/local/bin/ghi:19
```

**Comment by AlexChesters** [comment]
@lpanebr if you run `git list --config` can you is there is a `ghi.token` in the output?

**Comment by lpanebr** [comment]
Not actually ..

```bash
(develop)$ git --version 
git version 1.7.9.5
hub version 1.12.0-4-g3dc1784

(develop)$ git list --config
git: 'list' is not a git command. See 'git --help'.

Did you mean one of these?
        bisect
        rev-list
```

**Comment by AlexChesters** [comment]
@lpanebr sorry, should really proof-read more! I meant `git config --list`

**Comment by lpanebr** [comment]
ok, I see the `ghi.token=......mytolkenhere....`


I even deleted it on github and redid the `ghi config --auth`

**Comment by lpanebr** [comment]
wait! now it worked!

I had do close all terminals and open again.

![image](https://cloud.githubusercontent.com/assets/129185/10589827/34fb5b58-768c-11e5-8e85-afdce61f8130.png)



THANKS!!!!! \o/ :100:

**Comment by AlexChesters** [comment]
Ha, how strange! Please we got it working for you @lpanebr :smile: 

Enjoy `ghi` and thank you!

**Comment by lpanebr** [comment]
I already enjoyed it. Now I'm gonna love it!

Better only if I were able to (somehow) paste images from the clipboard
like I do on the web!!!  hahahaha

**Comment by AlexChesters** [comment]
@lpanebr that might be slightly outside the scope of `ghi` :wink:

Glad you enjoy it!
