### ISSUE TITLE
Authentication issue on OS X 10.11

### ISSUE THREAD

**Issue by melvinsh** [stephencelis/ghi#246]
I'm unable to use `ghi` on OS X 10.11 (I'm aware beta versions aren't usually supported). 

```
➜  repo git:(development) ✗ ghi config --auth melvinsh
Enter melvinsh's GitHub password (never stored):     ✔
Two-factor authentication code: ******
✔︎ Token saved to keychain.
```

```
➜  repo git:(development) ghi
⠒security: SecKeychainSearchCopyNext: unknown error -25300=ffffffffffff9d2c
#
Authorization required.

Please run 'ghi config --auth <username>'
```

**Comment by bobwaycott** [comment]
I'm also seeing the same behavior on 10.10.5

**Comment by sk7** [comment]
same here. installed `ghi` for the first time today. (via brew)

when i run `ghi config --auth sk7` again it gives me this:

```
% ghi config --auth sk7
Enter sk7's GitHub password (never stored):          ⠉security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
                                                     ✔
A ghi token already exists!

Please revoke all previously-generated ghi personal access tokens here:

  https://github.com/settings/applications
```

**Comment by chrismcg** [comment]
I had this because I had an old entry in the keychain. Deleting that, the application token on github, and removing the `[ghi]` entry from ~/.gitconfig then doing git config --auth made things work again.

**Comment by AlexChesters** [comment]
@melvinsh @bobwaycott have you tried @chrismcg's solution to this? If so, can you advise whether or not it works? Thanks!

**Comment by AlexChesters** [comment]
I'm going to close this now, please reopen if @chrismcg's solution doesn't fix this.

**Comment by chadrik** [comment]
I just had this same issue with ghi 1.1.1.  I'm unclear on what entry I should delete from my keychain.  This is the first time that I've used `ghi` so is this a conflict with another github application?  These are the entries related to github:

<img width="730" alt="screen shot 2016-05-23 at 1 09 37 pm" src="https://cloud.githubusercontent.com/assets/63251/15483056/b05c436a-20e7-11e6-9ba5-e48fe7b19f81.png">

**Comment by chadrik** [comment]
In case anyone else ends up here, I had to delete the entries labeled "internet password"

**Comment by kiddrew** [comment]
I followed the suggestions and I'm still unable to auth on OSX 10.11.2

**Comment by kiddrew** [comment]
Not sure what was different, but I deleted all passwords and the ghi token in github and recreated and it worked the second time.
