### ISSUE TITLE
wondering how you made that sweet animation

### ISSUE THREAD

**Issue by zzz6519003** [stephencelis/ghi#262]
:beer:

**Comment by AlexChesters** [comment]
Sounds like something you'll have to ask @stephencelis. It seems like the kind of thing that should be answered over email rather than an issue though so I'll close this for now

**Comment by stephencelis** [comment]
Check out https://github.com/stephencelis/ghi/blob/855ee411c486602e7603e18a59f3a5ea82effa19/lib/ghi/formatting.rb#L24-L32 ;)

**Comment by zzz6519003** [comment]
holy that was magic
