### ISSUE TITLE
Support personal access tokens 

### ISSUE THREAD

**Issue by dcode** [stephencelis/ghi#265]
I use 2FA for securing access to my repositories. As such, I seemingly cannot use the current ghi approach. I tried using a personal access token, which appeared to have worked (got a green check mark), but then ghi responds with:

~~~~~~~~~~~~
$ ghi config --auth dcode
Enter dcode's GitHub password (never stored):        ✔
This API can only be accessed with username and password Basic Auth
~~~~~~~~~~~~

**Comment by AlexChesters** [comment]
Hi @dcode,

`ghi` does currently support the use of `2FA`. This is the output I get when running `ghi config --auth alexchesters`
```
22:04:26-chesta02~/Desktop/code$ ghi config --auth alexchesters
                                                     ✔
Two-factor authentication code:
```

Can you run `ghi --version` please?

**Comment by dcode** [comment]
~~~~~~~
$ ghi --version
ghi version 1.0.3
~~~~~~~

I installed via Homebrew. I’ll pull the master.

—
Derek Ditch
derek@criticalstack.com
GPG: 0x2543A3B5

**Comment by dcode** [comment]
I got it to work. It wasn't clear to me from the initial prompt to put my regular password, so I tried a personal access token.
