### ISSUE TITLE
Display assignees on a list of issues

### ISSUE THREAD

**Issue by gitusp** [stephencelis/ghi#269]
I have made a little change to display assignees on a list of issues.
![screen shot 2016-01-16 at 00 05 34](https://cloud.githubusercontent.com/assets/2055516/12356365/a55a2778-bbe5-11e5-9417-5941ec1e2df6.png)
_Where yellow gitusp is me and gray lemusp is not me._

(current ghi shows only yellow @ when an issue is assigned to me.)
![screen shot 2016-01-16 at 00 05 23](https://cloud.githubusercontent.com/assets/2055516/12356478/47300f04-bbe6-11e5-99f0-79b82a139785.png)

---

I'm not sure that it's an **improvement** or **not** -- personally, I'd like to see who is assigned to what.
If you think it's an improvement, I'll open a pull-request.
Otherwise, please close this issue.

Thanks.

---

https://github.com/gitusp/ghi/tree/display-assignees

**Comment by AlexChesters** [comment]
I definitely think this is an improvement and I'd be really interested in it! Please open a PR :smile:

**Comment by stephencelis** [comment]
Same. Looks great!

**Comment by gitusp** [comment]
Thank you! I'll open a pull-request soon.
