### ISSUE TITLE
Unable to use ghi in some github projects.

### ISSUE THREAD

**Issue by mrkiko** [stephencelis/ghi#271]
The program doesn't work in some circumstances:

My problem is showing on:
https://github.com/Tox/toxic.git

[mrkiko@gatosaldo ghi]$ cd ../toxic
[mrkiko@gatosaldo toxic]$ ghi show 336

/usr/bin/ghi:4238:in `pull_request?': undefined method `[]' for nil:NilClass (NoMethodError)
        from /usr/bin/ghi:4221:in `execute'
        from /usr/bin/ghi:2762:in `execute'
        from /usr/bin/ghi:91:in `execute'
        from /usr/bin/ghi:4285:in `<main>'
[mrkiko@gatosaldo toxic]$ ghi show 378

/usr/bin/ghi:4238:in `pull_request?': undefined method `[]' for nil:NilClass (NoMethodError)
        from /usr/bin/ghi:4221:in `execute'
        from /usr/bin/ghi:2762:in `execute'
        from /usr/bin/ghi:91:in `execute'
        from /usr/bin/ghi:4285:in `<main>'

Changing project, from toxic to toxcore: at url
git://github.com/irungentoo/toxcore.git
it works fine!

[mrkiko@gatosaldo toxic]$ cd ../toxcore
[mrkiko@gatosaldo toxcore]$ ghi show 1511

1511: Re-format to reduce image file by 50%[0m[m
@romik[0m-g opened this pull request 46 minutes ago.  [3m[4m open [3m[0m [m

    Dockerfile has been re-formatted and image being built to reduce its' size from ~442.2MB to ~188.3MB. Idea is in leaving [m
    only one RUN statement, and inside it to perform build, install and cleanup. Change also cleans up build dependencies.[m

**Comment by mrkiko** [comment]
In my case, "git remove -v" seems to be up to date.
But I don't know exactly how this works right now.

**Comment by AlexChesters** [comment]
I've just tried it on a fresh clone of the repo you listed and it worked fine for me. Can you run `ghi --version` and post the output please?

**Comment by mrkiko** [comment]
Oh - the problem seems to be disappeared. Infact now it works with a 
freshcly cloned repo and even with my non-freshly cloned one.
Sorry guys, and thank you for the attention and help. This software is 
being very helpful to me, not only a matter of confort in my opinion.
Thank you.
