### ISSUE TITLE
Can't install on Ubuntu

### ISSUE THREAD

**Issue by krlmlr** [stephencelis/ghi#276]
I ran

```
sudo gem install ghi
```

with a success message. Now:

```
$ ghi
/var/lib/gems/2.1.0/gems/ghi-1.1.0/bin/ghi:4:in `<top (required)>': cannot load such file -- ghi (LoadError)
	from /usr/local/bin/ghi:22:in `load'
	from /usr/local/bin/ghi:22:in `<main>'
```

I'm at a loss.

**Comment by AlexChesters** [comment]
Can you post the output of the success message you mentioned?

**Comment by AlexChesters** [comment]
Also, can you post the output of `which ghi`?

**Comment by krlmlr** [comment]
At the root prompt:

```
# gem install ghi
Successfully installed ghi-1.1.0
Parsing documentation for ghi-1.1.0
Done installing documentation for ghi after 0 seconds
1 gem installed
# which ghi
/usr/local/bin/ghi
# locate ghi.rb
/var/lib/gems/2.1.0/gems/ghi-1.1.0/lib/ghi.rb
```

**Comment by AlexChesters** [comment]
That's really strange, unfortunately I don't have an Ubuntu machine to debug this on. Do you have access to an OS X machine? Can you reproduce it on there?

**Comment by krlmlr** [comment]
I can't replicate it in a shiny new Docker image. There's no point for me in trying to replicate the OS X install.

I guess my Ruby installation/configuration is fubar. What are the environment variables and configuration files to look after?

**Comment by AlexChesters** [comment]
Thanks for trying that @krlmlr, glad to hear you can't reproduce on a clean setup!

I'm not too sure what you mean by your last question?

**Comment by krlmlr** [comment]
How can I troubleshoot the installation issues on my "live" system? Do I need to check any specific env vars/configuration files? (Closing, as this doesn't seem to be a ghi problem.)
