### ISSUE TITLE
license: json-pure?

### ISSUE THREAD

**Issue by onlyjob** [stephencelis/ghi#277]
The following [fragment](../blob/master/LICENSE#L6) of `LICENSE` file is ambiguous:

    json-pure © Genki Takiuchi

Please clarify which part of _ghi_ is copyrighted as above. Thanks.

**Comment by onlyjob** [comment]
Besides Alex Chesters's copyright statement is missing...

**Comment by AlexChesters** [comment]
This will have to be answered by @stephencelis as he was the one who added that fragment to the `LICENSE` file.

What do you mean by `Besides Alex Chesters's copyright statement is missing...`?

**Comment by stephencelis** [comment]
> Please clarify which part of ghi is copyrighted as above. Thanks.

GHI embeds a JSON-parsing library when compiled into a single file. A quick search on GitHub would have brought you here: A quick search on GitHub would bring you here: https://github.com/genki/json

We should, however, be able to remove `json-pure` as a dependency given that Ruby has been shipping with `json` standard for awhile now.

**Comment by AlexChesters** [comment]
@stephencelis, are you able to answer @onlyjob's query?

**Comment by AlexChesters** [comment]
Where is `json-pure` defined as a dependency @stephencelis?

**Comment by stephencelis** [comment]
As far as adding Alex to the LICENSE file, that's really up to him ;)

Typically licenses remain bound to the original author/owner of the code, though I'm fine adding more people to it as they contribute as much as Alex has!

**Comment by stephencelis** [comment]
@AlexChesters It's embedded here:

https://github.com/stephencelis/ghi/blob/master/lib/ghi/json.rb

I'd experiment with removing it entirely, seeing what breaks, and replace the requires with `require 'json'`.

**Comment by AlexChesters** [comment]
I agree with @stephencelis that licenses remain bound to the original author/owner of the code, and given that I currently have no desire to put myself in the `LICENSE` file I'm not planning to do anything to address that.

On the second point I'm planning to do what @stephencelis has suggested re `json-pure`.

**Comment by AlexChesters** [comment]
Once/If #278 gets merged this issue will be resolved.

**Comment by onlyjob** [comment]
Thanks for quick replies everyone. :)

> What do you mean by Besides Alex Chesters's copyright statement is missing...?

Well that copyright statement is missing in the LICENSE file. A something like

    Copyright 2015 Alex Chesters <myemail@domain.com>

I see that there are many contributors but no copyrights are documented...
Confusing thing about compyrights is that scope of "json-pure © Genki Takiuchi" is unclear. Apparently it applies to 3rd party component unless Genki Takiuchi was also contributing to this project...

Bundled copy of json.rb should be better documented as it is difficult to identify it in source tree due to lack of licensing information. It would be great to mention its origin (e.g. project URL).

Bundled `json.rb` is not the same as https://github.com/genki/json which is GPL-2 licensed...

**Comment by stephencelis** [comment]
@onlyjob json-pure and its reference in the LICENSE are to be removed.

> I see that there are many contributors but no copyrights are documented...

LICENSE files and copyrights do not document every contributor to a project.

**Comment by onlyjob** [comment]
Thanks. :)

**Comment by AlexChesters** [comment]
This has now been closed, as `json-pure` has now been removed from this library (as it's functionality is now provided by Ruby itself), and I have no burning desire to add myself to the `LICENSE`. As @stephencelis has pointed out:
> LICENSE files and copyrights do not document every contributor to a project.

**Comment by onlyjob** [comment]
Thanks.

Lack of contributor's copyright statements is not ideal but should be acceptable...

**Comment by AlexChesters** [comment]
As far as I'm aware it's uncommon to list contributors in the LICENSE file, so I think that's why we've decided against it here

**Comment by onlyjob** [comment]
It is not that uncommon to list copyrights of significant contributors in LICENSE and there is already one contributor listed. It is convenient when copyright information is in one place. Sometimes LICENSE file is reserved for canonical text of the license with list of copyright holders in README.
The question whether you guys are going to maintain copyright attributions or not.
Without contributor license agreement to transfer copyright ownership copyright holders are not limited to the only one mentioned in LICENSE. Some projects use word "authors" in copyright attribution, some maintain list of contributors for copyright purposes...

**Comment by AlexChesters** [comment]
Anyway, I feel like we're getting carried away here. I have no desire to maintain copyright attribution so that's the main reason why the LICENSE file only contains Stephen's name

**Comment by onlyjob** [comment]
Fair enough, let's move on for now. Thanks.

**Comment by onlyjob** [comment]
@AlexChesters, may I ask you to tag json-less release please so I could upload it to Debian?
Thanks.
