### ISSUE TITLE
Subcommands help message clarification?

### ISSUE THREAD

**Issue by geier** [stephencelis/ghi#279]
It took me some time to find that the usage of most commands is `ghi command [-- [user/]repo` even for `show` etc. I think the help messages would be more helpful if it would like this:

```
usage: ghi show <issueno> [-- [username/]reponame]
```
With just `ghi show 256` the error message 'Not a GitHub repo' is show (which is correct, but not really helpful).

**Comment by stephencelis** [comment]
I'm sure @AlexChesters and I would both happily accept a PR with better language around that error!

**Comment by stephencelis** [comment]
(Do you have a suggestion? Something that urges a user to run from the directory of a GitHub repository or by using that suffix? Should be easy to add right here: https://github.com/stephencelis/ghi/blob/64aa83447b5ede3757483b6579f1a9df7c665ff2/lib/ghi/commands/command.rb#L60)

**Comment by AlexChesters** [comment]
I'd agree with @stephencelis, I'd be happy to see a PR around this :-)

**Comment by geier** [comment]
PRs are the new feature requests, I agree :smirk_cat:  I'll see if I can get to it.

I guess I ran ghi from a GitHub repository most of the time just as part of a normal workflow (as probably most people do) and when I didn't I was surprised it didn't work. I probably was just too tired to interpret `GitHub repository` correctly.

**Comment by AlexChesters** [comment]
If you were surprised when it didn't work then you won't be alone, let's get a pr :smile:
