### ISSUE TITLE
Milestone Documentation: How to add existing issue to existing milestone?

### ISSUE THREAD

**Issue by MosheBerman** [stephencelis/ghi#283]
Hey, thanks for an awesome gem! It's streamlining my workflow tremendously.

The documentation shown with the `ghi help milestone` command doesn't say how to add an existing issue to an existing milestone. Does this feature exist, and if so, how do I use it?

**Comment by AlexChesters** [comment]
`ghi edit <ISSUE_NO> -M <MILESTONE_NO>`

The documentation can be found in `ghi help edit`.
