### ISSUE TITLE
Unable to install via homebrew

### ISSUE THREAD

**Issue by tnorthcutt** [stephencelis/ghi#317]
```
brew install ghi
ghi: Unsatisfied dependency: pygments.rb
Homebrew does not provide special Ruby dependencies; install with:
  `gem install pygments.rb`
Error: An unsatisfied requirement failed this build.
```
Then:

```
gem install pygments.rb
Successfully installed pygments.rb-0.6.3
1 gem installed
```

Running `brew install ghi` again results in the same error message.

![image](https://cloud.githubusercontent.com/assets/796639/17339058/fe9a551e-589e-11e6-9194-2d5be0046bcb.png)

**Comment by AlexChesters** [comment]
@tnorthcutt thanks for reporting this, can you confirm your ruby version?

**Comment by tnorthcutt** [comment]
@AlexChesters you bet:

```
ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

**Comment by tnorthcutt** [comment]
Possibly relevant:

```
gem list pygments

*** LOCAL GEMS ***

pygments.rb (0.6.3)
```

**Comment by AlexChesters** [comment]
Managed to reproduce this locally using `2.3.1`.

**Comment by tnorthcutt** [comment]
It appears as though it may be a bug in Homebrew: https://stackoverflow.com/questions/20875941/how-does-homebrew-check-for-installed-gems#comment36203414_20887156

**Comment by AlexChesters** [comment]
Good spot @tnorthcutt, based on that SO question, can you check that correct `ruby` is first in your path?

**Comment by tnorthcutt** [comment]
It wasn't, but changing that doesn't seem to have had an impact. In fact, now (after uninstalling pygments and ghi to test the fix), my workaround doesn't work either 😂 .

Computers ¯\_(ツ)_/¯

**Comment by tnorthcutt** [comment]
Update: my workaround (`when :ruby then %W[/usr/bin/env ruby -rubygems -e "require\ '#{@import_name}'"]`, note double quotes around the `require` statement) is working again - I'd typo'd it.

Still no luck with this working without that, so I'm thinking this is a Homebrew issue. Closing for now; feel free to reopen if you'd like. If I can replicate on another machine I may open an issue with the Homebrew project.

**Comment by tomkyle** [comment]
This helped me around this on OS X Capitan. Maybe the first general update is not neccessary, but it needed to sudo-install the pygments.rb:

```
$ sudo gem update --system
$ sudo gem install pygments.rb
```
After that:

````
$ brew install ghi
... stuff ...
🍺  /usr/local/Cellar/ghi/1.2.0: 6 files, 93.3KB, built in 4 seconds
````

Done!
