### ISSUE TITLE
WISH: Cache for offline access

### ISSUE THREAD

**Issue by HenrikBengtsson** [stephencelis/ghi#319]
First time user here; ghi seems to be a very nice and powerful too. Thxs.

I found ghi because I was looking for a tool to view my GitHub issues while offline.  Using ghi, I can now pull down issues from my repository using something like:
```sh
issues=$(ghi list | grep -E "^ *[0-9]+ +" | sed -E 's/^ *([0-9]+) +.*/\1/g')
mkdir -p .ghi/issues/
for ii in $issues; do ghi show $ii > .ghi/issues/$ii.txt; done
```
This is "good enough" when I know in advance that I'm going to be working on my code while offline (=no internet access).

However, would it be possible to provide a layer for ghi that keeps a cache of `ghi list` and `ghi show` etc locally and which can be accessed as a fallback when the server cannot be accessed?  This would clearly be for read-only access, so not for updates.

I understand that this could be a quite daunting task to implement, but I just wanted to throw out the idea.

**Comment by HenrikBengtsson** [comment]
Sorry, should have searched for previous requests before posting.  I see that this is a duplication of Issue #60 ("Support offline use").  Closing again.

**Comment by jtoy** [comment]
@HenrikBengtsson  did you find a better solution for managing this? looking for a way to work in offline mode and then later be able to push and sync with github. this works great as a first step for read only.

**Comment by HenrikBengtsson** [comment]
No other solutions. OTH, I haven't looked and I haven't used ghi that much either since (or any alternatives).
