### ISSUE TITLE
Support open in #love editor

### ISSUE THREAD

**Issue by fuchao2012** [stephencelis/ghi#323]
We open blogs in github by issue,  ghi helps a lot.

But `vi` is not the best editor for bloger.

So, can i edit a issue in `sublime` or other editor?

**Comment by AlexChesters** [comment]
You can set the editor that `ghi` uses in [many different ways](https://github.com/stephencelis/ghi/blob/master/lib/ghi/editor.rb#L26-L32). The easiest is probably to set the environment variable `EDITOR`.
