### ISSUE TITLE
NPM packaging please 

### ISSUE THREAD

**Issue by iandstanley** [stephencelis/ghi#324]
Would love to see an npm packaged copy of this on the npm registry

**Comment by stephencelis** [comment]
@iandstanley Do you have examples of Ruby projects being distributed with npm? npm is generally used to distribute Node packages, whereas this project is a Ruby project (and available via Homebrew and RubyGems).

**Comment by stephencelis** [comment]
Closing for now. Please feel free to chime in if you'd like to continue the discussion!
