### ISSUE TITLE
Programmatic auth

### ISSUE THREAD

**Issue by joscha** [stephencelis/ghi#335]
I want to use `ghi` in CI - it seems however as if the user/password can't be passed to `ghi` - `ghi help config` only shows how to pass the user - is there a way to use environment variables to configure the auth part of ghi? If not, would you accept a pull request that adds this feature?

**Comment by shubhamshuklaer** [comment]
https://github.com/stephencelis/ghi/blob/b321f7f28176e84d5ec2f7d6e5a6b36257240040/man/ghi.1
GITHUB_USER
GITHUB_PASSWORD
GHI_TOKEN

**Comment by joscha** [comment]
O, man pages, 👍  Thank you!
