### ISSUE TITLE
feature request for ghi list: flexible formatting

### ISSUE THREAD

**Issue by sefk** [stephencelis/ghi#61]
Big fan of these tools -- use them every day for managing [our project] [1], thanks!. This is a new feature request.
  [1]: https://github.com/Stanford-Online/class2go

I'd love to be able to control what fields are output when doing a ```ghi list```.  Some examples:
- when listing by label (ie my P0 bugs) I'd love to see what milestones they are assigned to
- when listing by milestone (our sprints) I'd love to see who is assigned to what

And that sort of thing.  But instead of a bunch of onesy-twoesy options, seems like flexibility would get me most of what I'm looking for.

Thanks.

**Comment by AlexChesters** [comment]
Closing as it looks like this is now implemented.
