### ISSUE TITLE
Support all names for remotes, not just 'origin'

### ISSUE THREAD

**Issue by ChimeraCoder** [stephencelis/ghi#85]
This only seems to work on the remote named 'origin'. If your remote corresponding to GitHub is named something else (ie, 'github'), it won't work.

I get the following:

```
$  ghi show 1
Not a GitHub repo.

usage: ghi show <issueno>

    -p, --patch
    -w, --web

$ git remote
github
heroku

$  git remote rename github origin

$ ghi show 1
#1: Create a template that will display a list of RSS feeds passed to 
it
@ChimeraCoder opened this issue 54 days ago.  closed  (1 comment)
@ChimeraCoder is assigned. 

..etc.
```

**Comment by unitof** [comment]
@stephencelis When you say it looks for the `upstream` remote, do you mean it looks for a remote literally named `upstream`, or it tries to detect the upstream remote for the current branch?

I'm experiencing the former but would like to confirm.
